apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "codeserver-helm-chart.fullname" . }}-projects
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}